### ISSUE TITLE
How to return different responses for the same endpoint ?

### ISSUE THREAD

**Issue by vcamposs** [mrak/stubby4node#102]
For exemple : 

Endpoint: /hey/0011
  hit:1 -> {"hey":"a"}
  hit:2 -> {"hey":"b"}

**Comment by mrak** [comment]
Like this?

From https://github.com/mrak/stubby4node#response

> The `response` property can also be a yaml sequence of responses that cycle as each request is made.

```yaml
- request:
    url: /hey/0011
  response:
  - status: 200
    body: '{"hey":"a"}'
  - status: 200
    body: '{"hey":"b"}'
```
