### ISSUE TITLE
Serve different JSON to queryParam endpoint

### ISSUE THREAD

**Issue by toddmotto** [mrak/stubby4node#15]
My first endpoint returns a default JSON Object, which a user fills in, when they hit the same endpoint with query params, I want to serve back the specific Object that they'd have previously filled in client side as the model.

So far I've got this:

``` yaml
### NO QUERY STRING
- request:
    method: GET
    url: ^/rest/form$
  response:
    headers:
      content-type: application/json
    file: form_create_request.json
    latency : 100

### QUERY STRING
- request:
    method: GET
    url: ^/rest/form$
    query:
      workflowId: "^[0-9]{16}$"
  response:
    headers:
      content-type: application/json
    file: form_saved_request.json
    latency : 100

```

You see the `url` property is the same, but the `file` served back from the second URL doesn't work (pretty sure this is because I'm mapping the same URL twice, just one has query params). Is there a way to hit the same endpoint but when a query string is present return different JSON? I've had a look through the docs but to no avail. Thanks!
