### ISSUE TITLE
Switch based on request body

### ISSUE THREAD

**Issue by atwright147** [mrak/stubby4node#37]
Is it possible to use stubby to return a different response based on the payload it receives?

I would like to be able to have a YAML file similar to the following. If a request comes in with the `cardNumber` **4000000000000010** I would like stubby to return a *400 header* and if it receives a `cardNumber` of **4242424242424242** I would like a *200* etc...

This doesn't seem to work with my current set up.

```yaml
-  request:
      url: ^/cards/activate
      method: POST
      headers:
         content-type: application/json
      post: >
         {"cardNumber":"4000000000000010","expiryMonth":\d{1,2},"expiryYear":\d{4}|\d{2},"dob":"\d{4}-\d{1,2}-\d{1,2}"}
   response:
    - status: 400
      latency: 1000
      headers:
         content-type: application/json
         server: stubbedServer/4.2
      body: >
         {
            "errorMessage": "Dunno, something went wronged"
         }

-  request:
      url: ^/cards/activate
      method: POST
      headers:
         content-type: application/json
      post: >
         {"cardNumber":"4242424242424242","expiryMonth":\d{1,2},"expiryYear":\d{4}|\d{2},"dob":"\d{4}-\d{1,2}-\d{1,2}"}
   response:
    - status: 200
      latency: 1000
      headers:
         content-type: application/json
         server: stubbedServer/4.2
      body: >
         {
            "token": "MWUxMjBkZWYzNzk0YWYwNTdiMDE5YjA1NDY2ZGRiNGQwYWNhNzZlZGNlYTYxYWVmNGEyYzhmMGI5YjgzOTc0Zg==",
            "authenticated": true,
            "validationErrorDTO": null
         }
```

Many thanks,

Andy
