### ISSUE TITLE
match against parameters

### ISSUE THREAD

**Issue by alex-moreno** [mrak/stubby4node#40]
I'm trying to do something like that:

- request:
....
    query:
      serviceId: "s009"

  response:
    file: destinations/destination-by-service-id-$serviceId.json
...

So the serviceId would match the file destination-by-service-id-$serviceId.json instead of having to create several files to match different service id's, like s008, s010, etc...

Is that something we can do with stubby?

Thank you very much in advance.

**Comment by mrak** [comment]
[Dynamic Token Replacement](https://github.com/mrak/stubby4node#dynamic-token-replacement)

[Where to specify the template](https://github.com/mrak/stubby4node#where-to-specify-the-template)

You can specify a single file with token replacement _inside_ the file according to the value encountered in `query.serviceId`.

```yaml
- request:
    ...
    query:
      serviceId: "(s[0-9]{3})"
  response:
    file: destinations/destination-by-service-id.json
    ...
```

__destinations/destination-by-service-id.json__
```json
{
  "serviceId": "<% query.serviceId[1] %>"
}
```

Let me know if this satisfies your use-case!
