### ISSUE TITLE
Optional query parameters

### ISSUE THREAD

**Issue by Droogans** [mrak/stubby4node#43]
It'd be nice to mark certain query parameters as optional. I have two calls that return the same data, but are formatted differently in the UI.

```yaml
# full search results
-   request:
        url: ^/api/global-search/search$
        method: GET
        query:
            q: test
    response:
        status: 200
        file: test/api-mocks/responses/global-search/test-results.json
```

```yaml
# "preview" (suggestions) results
-   request:
        url: ^/api/global-search/search$
        method: GET
        query:
            page_size: ^[\d]+$
            q: test
    response:
        status: 200
        file: test/api-mocks/responses/global-search/test-results.json
```

Can I merge these two calls into one? I would like to avoid duplicating all new calls this way.

Maybe something like this?

```yaml
-   request:
        url: ^/api/global-search/search$
        method: GET
        query:
            page_size: $([\d]+)?^ # can be completely blank, therefore will match if `page_size` is missing
            q: test
    response:
        status: 200
        file: test/api-mocks/responses/global-search/test-results.json
```
