### ISSUE TITLE
The order or the parameters have more influence?

### ISSUE THREAD

**Issue by uhtred** [mrak/stubby4node#48]
If i change the order in the yaml file, the first is the match.

```
- request:
    url: ^/profile$
    method: POST
    post: >
      .*Exist.*
  response:
    status: 422
    latency: 100
    headers:
       content-type: application/json
    body: >
      {
        "errorCode": "PROFILE_ALREADY_EXISTING"
      }
```
```
- request:
    url: ^/profile$
    method: POST
  response:
    status: 200
    latency: 1000
    headers:
       content-type: application/json
    body: >
        {
          "id": 1,
          "name":"New Perfil"
        }
```
