### ISSUE TITLE
No URL / query param match when string contains encoding characters

### ISSUE THREAD

**Issue by kyranjamie** [mrak/stubby4node#55]
Having some issues with URLs containing character codings. Boiled it down to this config.

```yaml
- request:
    url: ^/dashboard
    query:
      q: '%7B'
    method: POST
  response:
    - file: resp.json
      headers: {Content-Type: application/json}
      status: 200
```

Making a req with httpie
```
http POST http://localhost:8882/dashboard?q=%7B
```
returns `404 [stubs]/member/ajax/es/websites/dashboard?q=%7B is not a registered endpoint`

`%7B` is a `{` which, unfortunately, appears in a query param of an API response I'm trying to mock.

In an idea world the API I'm trying to mock wouldn't use encoded query params. It can happen though, so it'd be nice if stubby handled this.

**Comment by mrak** [comment]
Does it work if you use `'{'` in the yaml configuration?

```yaml
- request:
    url: ^/dashboard
    query:
      q: '{'
    method: POST
  response:
    - file: resp.json
      headers: {Content-Type: application/json}
      status: 200
```

**Comment by kyranjamie** [comment]
Nope, doesn't work either.

**Comment by mrak** [comment]
This appears to work for me. Let me know what I should change to reproduce your testing API's example

```yaml
# configuration
- request:
    url: ^/dashboard
    query:
      q: '{'
    method: POST
  response:
    - body: 'matched!'
      headers: {Content-Type: application/json}
      status: 200
```

```
$ curl -X POST 'localhost:8882/dashboard?q=%7B'
matched!

$ curl -X POST 'localhost:8882/dashboard?q=\{'
matched!
```
