### ISSUE TITLE
Request new feature to work for HTTP OPTIONS request

### ISSUE THREAD

**Issue by DDDDDanica** [mrak/stubby4node#63]
Something like this would be so handy :)
```
-  request:
      url: ^/give/me/options$
      method: OPTIONS
   response:
      headers:
         content-type: application/json
      body: >
         [1, 2, 3]
```

**Comment by mrak** [comment]
Sorry for the late reply. Your example should already work with stubby. Have you tried it?

**Comment by mrak** [comment]
Also, welcome to Github and submitting issues!

**Comment by castro150** [comment]
Hi! I'm with a problem related to OPTIONS method. Trying to respond to a similar request, I got the error:

`events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.write (_http_outgoing.js:485:15)
    at callback (/home/rafael/.nvm/versions/node/v7.9.0/lib/node_modules/stubby/src/portals/stubs.js:46:18)
    at Endpoints.found (/home/rafael/.nvm/versions/node/v7.9.0/lib/node_modules/stubby/src/models/endpoints.js:128:5)
    at Endpoints.find (/home/rafael/.nvm/versions/node/v7.9.0/lib/node_modules/stubby/src/models/endpoints.js:102:17)
    at IncomingMessage.<anonymous> (/home/rafael/.nvm/versions/node/v7.9.0/lib/node_modules/stubby/src/portals/stubs.js:54:22)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

Then the stubby simply crashes. Apparently the response is ending early, before the body is written. How can I solve this?

**Comment by mrak** [comment]
It appears you are using a development version of node.js. Does the same thing occur on the latest stable 6.x version of node?

**Comment by xlevel** [comment]
I am having the same issue.

I'm using Stubby with the LTS 10.x version of node and the following config:

```
- request:
    method: [OPTIONS]
    url: ^/(.*)$

  response: 
    status: 200
```
