### ISSUE TITLE
Support for handling all live requests?

### ISSUE THREAD

**Issue by tgabre** [mrak/stubby4node#80]
I'm using a single yaml file and Stubby to handle all live requests to an api.
Is there any support for Stubby to use a single file to dynamically handle all live requests, as such?

```
-  request:
      url: ^/.+
      method: [GET, POST]
   response:
      status: 302
      headers: 
         Location: https://liveEndpoint.com<% url[0] %>
```

As of right now, all requests going through Stubby are GETs despite the client app sending out GETs and POSTs.
