### ISSUE TITLE
Multiple header Set-Cookie in response headers

### ISSUE THREAD

**Issue by zrjosser** [mrak/stubby4node#88]
I need in the response headers return something like:

Set-Cookie: ...; Secure; HttpOnly
Set-Cookie: ....blah
Set-Cookie: .....

In the yaml cannot have multiple keys whith same name... how to handle this?

**Comment by mrak** [comment]
Does this work for you?

```yaml
- request:
    url: /duplicated/header
  response:
    headers:
      Set-Cookie:
      - key=value
      - foo=bar
```
