### ISSUE TITLE
Query parameter matching issue

### ISSUE THREAD

**Issue by olivierodo** [mrak/stubby4node#92]
Hi there 👋,
Thank you for this nice component!
Currently I have an issue on a specific query parameter matching.
I try to mock the url: `https://localhost:3000/v1/api.json?rss_url=https://www.youtube.com/feeds/videos.xml?channel_id=xxx`

However when i'm using the following stub:
```yaml
request:
  url: /v1/api.json
  method: GET
  query:
    rss_url: "https://www.youtube.com/feeds/videos.xml?channel_id=xxx"
response:
  status: 200
  headers:
     content-type: application/json
  body: >
    {
        "feed": {
       }
    }
```

Stubby can't find the match 😅...

Any though ?
