### ISSUE TITLE
Not able to match a URL which doesn't have path but have parameters

### ISSUE THREAD

**Issue by kapadiapankit** [mrak/stubby4node#94]
Hey @mrak 

Thanks for the package. I've been using it since long and today I got a little different scenario which I am unable to configure.

Not able to match a URL which doesn't have path and does have many parameters.
Example URL: `https://hostname.com/?param1=a&param2=b`

Tried this:
```
- request:
    url: ^/
    params:
      param1: a
      param2: b
    method: GET
    headers:
      content-type: application/xml
  response:
    status: 200
    file: responses/xml_successful.xml
```
