### ISSUE TITLE
Reply 404 whenever no body and file not found

### ISSUE THREAD

**Issue by rstriquer** [mrak/stubby4node#96]
If file is not found when replying it uses body but it would be nice to return 404 whenever the body part is not placed/defined in yml control file.

Sample control yml part related to question
```yaml
- request:
    url: ^/api/prod/(\d*)$
    method: GET
  response:
    status: 200
    file: data/api/prod/<% url[1] %>.json
````

Would this proposal be something useful or does it have a way to config this way already?
